### ISSUE TITLE
project and item type list warning

### ISSUE THREAD

**Issue by casakawa-jama** [CapstoneBitsPlease/JamaConnectFrontend#50]
getting the following warning on the project and item type list :
```
Warning: Each child in a list should have a unique "key" prop.
```

this is low priority.. but if you have a duplicate project name or item type name then this warning will turn into an error.

you can resolve this by using the "key"  prop on your react elements that are repeating the lists.

**Comment by CapstoneBitsPlease** [comment]
This is fixed
